### ISSUE TITLE
Invalid use of Cmake argument '-H'

### ISSUE THREAD

**Issue by NGenetzky** [bast/gtest-demo#7]
Context:

```
git clone https://github.com/bast/gtest-demo.git
cd gtest-demo
cmake -H. -Bbuild
cd build
cmake --build .
```

Error:

```
cmake -H. -Bbuild
```

I think this is actually incorrect (but failing gracefully).  `-H` appears to be the help flag.

Suggestion:

```
git clone https://github.com/bast/gtest-demo.git
cd gtest-demo
cmake . -B build && cmake --build build
```

**Comment by bast** [comment]
Dear Nathan, thank you! `-H` actually works on some installations but is undocumented and I will change it following your suggestion.

**Comment by NGenetzky** [comment]
You're welcome. I used your demo as a starting point for a project, and so I wanted to contribute back.

The command seemed to run just fine, but at least on my version the `-H.` wasn't actually doing anything (anything beneficial at least).

**Comment by bast** [comment]
Glad to hear that it is useful - a fix coming up very soon.
